# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159e950b86d3907b357ed56e3a47ab1079c2d4e0fafb16acae6ef4025d7af35ac60d552de0d3f6bdcc85a82891e323723b64dcd436b091df191797a685e9cad6

test:
  secret_key_base: d73eaa160d84a786fba6ebfbdf95a4b689c6a6f2daaaea6081426bff5d155010aab3cd4dca258cc87f11a623a78a47677b92c2f73574041eb64ecc055fca24d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
